import Foundation

public enum ChumenConfigurationBuilder {
    // 这些顶层键由 GUI/CLI 设置统一接管，生成运行配置时必须覆盖用户 profile 里的同名值。
    private static let alwaysOverwrittenTopLevelKeys: Set<String> = [
        "mixed-port",
        "socks-port",
        "port",
        "redir-port",
        "tproxy-port",
        "external-controller",
        "external-controller-unix",
        "external-controller-cors",
        "external-ui",
        "external-ui-name",
        "external-ui-url",
        "secret",
        "allow-lan",
        "mode",
        "log-level",
        "ipv6",
        "unified-delay",
        "tun"
    ]

    public static func writeRuntimeConfig(
        settings: ChumenRuntimeSettings,
        paths: ChumenPaths,
        profileAppendixYAML: String = ""
    ) throws {
        try paths.ensureDirectories()

        let profileYAML: String?
        if let profilePath = settings.profilePath, !profilePath.isEmpty {
            profileYAML = try String(contentsOfFile: profilePath, encoding: .utf8)
        } else {
            profileYAML = nil
        }

        let yaml = runtimeYAML(
            profileYAML: profileYAML,
            settings: settings,
            socketPath: paths.externalControllerSocketURL.path,
            profileAppendixYAML: profileAppendixYAML
        )
        try yaml.write(to: paths.runtimeConfigURL, atomically: true, encoding: .utf8)
    }

    public static func runtimeYAML(
        profileYAML: String?,
        settings: ChumenRuntimeSettings,
        socketPath: String?,
        profileAppendixYAML: String = ""
    ) -> String {
        let base = normalizedBaseYAML(profileYAML)
        let globallyExtended = applyingAppendixYAML(settings.configAppendixYAML, to: base)
        let profileExtended = applyingAppendixYAML(profileAppendixYAML, to: globallyExtended)
        // 保留订阅和扩展中的代理、规则和 provider，只移除 Chumen 明确负责的运行时键。
        let stripped = removeTopLevelKeys(overwrittenTopLevelKeys(settings: settings), from: profileExtended)
        let overrides = topLevelOverrides(settings: settings, socketPath: socketPath)

        if stripped.isEmpty {
            return overrides
        }

        return [stripped, overrides].filter { !$0.isEmpty }.joined(separator: "\n\n")
    }

    private static func overwrittenTopLevelKeys(settings: ChumenRuntimeSettings) -> Set<String> {
        var keys = alwaysOverwrittenTopLevelKeys
        if settings.enableDNS || settings.enableTun {
            keys.insert("dns")
        }
        if !settings.hostsYAML.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            keys.insert("hosts")
        }
        return keys
    }

    public static func removeTopLevelKeys(_ keys: Set<String>, from yaml: String) -> String {
        let lines = yaml.components(separatedBy: .newlines)
        var result: [String] = []
        var skippingBlock = false

        // 这里是一个受控的浅层 YAML 处理器，只处理顶层键，避免引入完整 YAML 依赖。
        for line in lines {
            if skippingBlock {
                if line.isEmpty {
                    continue
                }
                if indentation(of: line) > 0 {
                    continue
                }
                skippingBlock = false
            }

            if let key = topLevelKey(in: line), keys.contains(key) {
                if topLevelValue(in: line).isEmpty {
                    skippingBlock = true
                }
                continue
            }

            result.append(line)
        }

        return result.joined(separator: "\n")
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    public static func topLevelKey(in line: String) -> String? {
        guard indentation(of: line) == 0 else { return nil }
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty, !trimmed.hasPrefix("#"), !trimmed.hasPrefix("-") else { return nil }
        guard let colonIndex = trimmed.firstIndex(of: ":") else { return nil }
        let key = trimmed[..<colonIndex].trimmingCharacters(in: .whitespaces)
        return key.isEmpty ? nil : key
    }

    private static func normalizedBaseYAML(_ profileYAML: String?) -> String {
        guard let profileYAML, !profileYAML.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return defaultProfileYAML
        }
        return profileYAML.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private static func topLevelOverrides(settings: ChumenRuntimeSettings, socketPath: String?) -> String {
        var lines = [
            "# Generated by Chumen",
            "mixed-port: \(settings.mixedPort)",
            "allow-lan: \(yamlBool(settings.allowLAN))",
            "mode: \(settings.mode.rawValue)",
            "log-level: \(settings.logLevel.rawValue)",
            "external-controller: \(settings.externalControllerHost):\(settings.externalControllerPort)",
            "secret: \(yamlQuoted(settings.secret))",
            "ipv6: \(yamlBool(settings.ipv6))",
            "unified-delay: \(yamlBool(settings.unifiedDelay))"
        ]

        if settings.socksEnabled {
            lines.insert("socks-port: \(settings.socksPort)", after: "mixed-port: \(settings.mixedPort)")
        }
        if settings.httpEnabled {
            lines.insert("port: \(settings.httpPort)", after: "mixed-port: \(settings.mixedPort)")
        }
        if settings.redirEnabled {
            lines.append("redir-port: \(settings.redirPort)")
        }
        if settings.tproxyEnabled {
            lines.append("tproxy-port: \(settings.tproxyPort)")
        }

        if let socketPath, !socketPath.isEmpty {
            lines.insert("external-controller-unix: \(yamlQuoted(socketPath))", after: "external-controller: \(settings.externalControllerHost):\(settings.externalControllerPort)")
        }
        if !settings.externalUI.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            lines.append("external-ui: \(yamlQuoted(settings.externalUI))")
        }
        if !settings.externalUIName.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            lines.append("external-ui-name: \(yamlQuoted(settings.externalUIName))")
        }
        if !settings.externalUIURL.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            lines.append("external-ui-url: \(yamlQuoted(settings.externalUIURL))")
        }
        if !settings.externalControllerCORSAllowOrigins.isEmpty {
            lines.append("external-controller-cors:")
            lines.append("  allow-private-network: \(yamlBool(settings.externalControllerCORSAllowPrivateNetwork))")
            lines.append("  allow-origins:")
            lines.append(contentsOf: settings.externalControllerCORSAllowOrigins.map { "    - \(yamlQuoted($0))" })
        }

        lines.append(contentsOf: tunLines(settings: settings))
        // TUN 依赖 DNS 劫持时，即使用户没有单独开启 DNS，也要生成 dns 段。
        if settings.enableDNS || settings.enableTun {
            lines.append(contentsOf: dnsLines(settings: settings))
        }
        if !settings.hostsYAML.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            lines.append("hosts:")
            lines.append(contentsOf: indentedBlock(settings.hostsYAML, spaces: 2))
        }

        return lines.joined(separator: "\n") + "\n"
    }

    private static var defaultProfileYAML: String {
        """
        proxies: []
        proxy-groups:
          - name: PROXY
            type: select
            proxies:
              - DIRECT
        rules:
          - MATCH,DIRECT
        tun:
          enable: false
          stack: gvisor
          auto-route: true
          strict-route: false
          auto-detect-interface: true
          dns-hijack:
            - any:53
        """
    }

    private static func tunLines(settings: ChumenRuntimeSettings) -> [String] {
        [
            "tun:",
            "  enable: \(yamlBool(settings.enableTun))",
            "  stack: \(settings.tunStack.rawValue)",
            "  device: \(yamlQuoted(settings.tunDevice.isEmpty ? "utun1024" : settings.tunDevice))",
            "  auto-route: \(yamlBool(settings.tunAutoRoute))",
            "  strict-route: \(yamlBool(settings.tunStrictRoute))",
            "  auto-detect-interface: \(yamlBool(settings.tunAutoDetectInterface))",
            "  mtu: \(settings.tunMTU)",
            "  dns-hijack:",
        ] + listLines(settings.tunDNSHijack.isEmpty ? ["any:53"] : settings.tunDNSHijack, indent: 4)
        + [
            "  route-exclude-address:"
        ] + listLines(settings.tunRouteExcludeAddress, indent: 4)
    }

    private static func dnsLines(settings: ChumenRuntimeSettings) -> [String] {
        let nameservers = settings.nameservers.isEmpty ? ChumenRuntimeSettings.defaultNameservers : settings.nameservers
        let defaultNameservers = settings.defaultNameservers.isEmpty ? ["system", "223.6.6.6", "8.8.8.8"] : settings.defaultNameservers
        var lines = [
            "dns:",
            "  enable: \(yamlBool(settings.enableDNS || settings.enableTun))",
            "  listen: \(yamlQuoted(settings.dnsListen))",
            "  enhanced-mode: \(settings.dnsMode.rawValue)",
            "  ipv6: \(yamlBool(settings.dnsIPv6))",
            "  fake-ip-range: \(yamlQuoted(settings.dnsFakeIPRange))",
            "  fake-ip-range6: \(yamlQuoted(settings.dnsFakeIPRange6))",
            "  fake-ip-filter-mode: \(settings.dnsFakeIPFilterMode.rawValue)",
            "  prefer-h3: \(yamlBool(settings.dnsPreferH3))",
            "  respect-rules: \(yamlBool(settings.dnsRespectRules))",
            "  use-hosts: \(yamlBool(settings.dnsUseHosts))",
            "  use-system-hosts: \(yamlBool(settings.dnsUseSystemHosts))",
            "  default-nameserver:"
        ]
        lines.append(contentsOf: listLines(defaultNameservers, indent: 4))
        lines.append("  nameserver:")
        lines.append(contentsOf: listLines(nameservers, indent: 4))
        lines.append("  fallback:")
        lines.append(contentsOf: listLines(settings.fallbackNameservers, indent: 4))
        lines.append("  proxy-server-nameserver:")
        lines.append(contentsOf: listLines(settings.proxyServerNameservers, indent: 4))
        lines.append("  direct-nameserver:")
        lines.append(contentsOf: listLines(settings.directNameservers, indent: 4))
        lines.append("  fake-ip-filter:")
        lines.append(contentsOf: listLines(settings.fakeIPFilters, indent: 4))
        lines.append("  fallback-filter:")
        lines.append("    geoip: \(yamlBool(settings.fallbackFilterGeoIP))")
        lines.append("    geoip-code: \(yamlQuoted(settings.fallbackFilterGeoIPCode))")
        lines.append("    ipcidr:")
        lines.append(contentsOf: listLines(settings.fallbackFilterIPCIDRs, indent: 6))
        lines.append("    domain:")
        lines.append(contentsOf: listLines(settings.fallbackFilterDomains, indent: 6))
        if !settings.nameserverPolicyYAML.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            lines.append("  nameserver-policy:")
            lines.append(contentsOf: indentedBlock(settings.nameserverPolicyYAML, spaces: 4))
        }
        return lines
    }

    private static func indentation(of line: String) -> Int {
        line.prefix { $0 == " " || $0 == "\t" }.count
    }

    private static func topLevelValue(in line: String) -> String {
        guard let colonIndex = line.firstIndex(of: ":") else { return "" }
        return String(line[line.index(after: colonIndex)...]).trimmingCharacters(in: .whitespaces)
    }

    private static func yamlQuoted(_ value: String) -> String {
        let escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }

    private static func yamlBool(_ value: Bool) -> String {
        value ? "true" : "false"
    }

    private static func listLines(_ values: [String], indent: Int) -> [String] {
        guard !values.isEmpty else {
            return ["\(String(repeating: " ", count: indent))[]"]
        }
        return values.map { "\(String(repeating: " ", count: indent))- \(yamlQuoted($0))" }
    }

    private static func indentedBlock(_ yaml: String, spaces: Int) -> [String] {
        let prefix = String(repeating: " ", count: spaces)
        return yaml
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .components(separatedBy: .newlines)
            .map { line in line.isEmpty ? "" : prefix + line }
    }

    private static func normalizedAppendixYAML(_ yaml: String) -> String {
        yaml.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private static func applyingAppendixYAML(_ appendixYAML: String, to yaml: String) -> String {
        let appendix = normalizedAppendixYAML(appendixYAML)
        guard !appendix.isEmpty else {
            return yaml.trimmingCharacters(in: .whitespacesAndNewlines)
        }

        let keys = topLevelKeys(in: appendix)
        let stripped = keys.isEmpty ? yaml : removeTopLevelKeys(keys, from: yaml)
        return [stripped, appendix]
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
            .joined(separator: "\n\n")
    }

    private static func topLevelKeys(in yaml: String) -> Set<String> {
        Set(yaml.components(separatedBy: .newlines).compactMap { topLevelKey(in: $0) })
    }
}

private extension Array where Element == String {
    mutating func insert(_ newElement: String, after existing: String) {
        guard let index = firstIndex(of: existing) else {
            append(newElement)
            return
        }
        insert(newElement, at: self.index(after: index))
    }
}
